/*
 * Gastos API REST
 * API REST de cadastro de gastos
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Gasto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiControllerApi
 */
@Ignore
public class ApiControllerApiTest {

    private final ApiControllerApi api = new ApiControllerApi();

    
    /**
     * criarGasto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void criarGastoUsingPOSTTest() throws ApiException {
        Gasto gasto = null;
        Object response = api.criarGastoUsingPOST(gasto);

        // TODO: test validations
    }
    
    /**
     * listarGasto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listarGastoUsingGETTest() throws ApiException {
        Long id = null;
        Object response = api.listarGastoUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * listarGastos
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listarGastosUsingGETTest() throws ApiException {
        Object response = api.listarGastosUsingGET();

        // TODO: test validations
    }
    
}
